# Generated by Django 4.2.5 on 2023-09-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0, verbose_name='Деньги'),
        ),
    ]
