# Generated by Django 4.2.5 on 2023-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.TextField(verbose_name='Промокод')),
                ('prize', models.IntegerField(verbose_name='Приз')),
                ('isActive', models.BooleanField(default=True, verbose_name='Действителен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
