# Generated by Django 4.2.5 on 2023-09-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_text',
            field=models.TextField(default='', verbose_name='Ответ на вопрос'),
        ),
    ]
