# Generated by Django 4.2.5 on 2023-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dis_grade',
            field=models.IntegerField(default=0, verbose_name='Оценка в минус'),
        ),
    ]
